<a href="https://colab.research.google.com/github/nikadekrahayuwindari-rgb/tugas-kelompok-dam/blob/main/tugas_kelompok_dam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Anggota Kelompok**

| No. | Nama Anggota | NIM |
|:---:|:---|:---:|
| 1 | Ni Kadek Rahayu Windari | 2501010176 |
| 2 | Yuliana Farida | 2501010372 |
| 3 | Clementin Christianingsi Mune Harum | 2501010363 |

---

### **1. Daftar Jenis Data**

Berikut adalah daftar jenis data yang dikelola dalam sistem informasi katalog UMKM perak Desa Celuk:

* **Profil UMKM**: Berisi data nama usaha, pemilik, alamat, kontak, dan deskripsi singkat usaha.
* **Logo & Foto Bengkel**: Gambar identitas visual untuk masing-masing UMKM.
* **Produk (Teks)**: Informasi detail produk meliputi nama, kategori, harga, berat perak, kadar (925/sterling), serta deskripsi produk.
* **Foto Produk**: Galeri foto dari beberapa sudut pengambilan gambar untuk setiap produk.
* **Video Produk/Proses**: Klip video pendek proses pembuatan kerajinan perak.
* **Kategori/Koleksi**: Pengelompokan jenis perhiasan seperti cincin, gelang, kalung, anting, dan lainnya.
* **Pengguna**: Autentikasi akun untuk admin, pengrajin, dan pembeli.
* **Pesanan/Inquiry**: Permintaan informasi dan pemesanan dari pembeli.
* **Ulasan & Rating**: Umpan balik dan penilaian dari pembeli.
* **Artikel Budaya**: Konten edukasi seperti sejarah perak Celuk, teknik filigree, dan lainnya.
* **Log Aktivitas**: Catatan riwayat login serta perubahan data untuk audit keamanan.

In [5]:
import os
import pandas as pd

# Memastikan direktori docs tersedia
os.makedirs('docs', exist_ok=True)

# ============================================================
# DATA KARAKTERISTIK BERDASARKAN KERANGKA 5W1H
# ============================================================
karakteristik_data = {
    "Jenis Data": [
        "Profil UMKM",
        "Logo & foto bengkel",
        "Produk (teks)",
        "Foto produk",
        "Video",
        "Kategori",
        "Pengguna",
        "Pesanan/inquiry",
        "Ulasan",
        "Artikel budaya",
        "Log aktivitas"
    ],
    "Apa": [
        "Teks terstruktur (Nama, pemilik, alamat, kontak, deskripsi)",
        "Gambar identitas (Logo dan dokumentasi tempat usaha)",
        "Teks & Angka (Nama, kategori, harga, berat perak, kadar 925, deskripsi)",
        "Gambar detail (Visual produk dari berbagai sudut)",
        "Video MP4 (Proses pembuatan perak filigree/detail produk)",
        "Teks pendek (Kategori perhiasan seperti cincin, gelang, kalung)",
        "Teks (Kredensial akun admin, pengrajin, dan pembeli dengan hash password)",
        "Teks & Angka transaksional (Detail pesanan dan permintaan pembeli)",
        "Teks & Angka (Feedback teks dan rating bintang dari pembeli)",
        "Teks & Gambar (Sejarah perak Celuk, teknik pembuatan, edukasi)",
        "Teks baris log (Riwayat sistem, waktu login, perubahan data)"
    ],
    "Siapa": [
        "Admin / Pengrajin",
        "Pengrajin",
        "Pengrajin",
        "Pengrajin",
        "Pengrajin",
        "Admin",
        "Semua Pengguna",
        "Pembeli",
        "Pembeli",
        "Admin",
        "Sistem (Otomatis)"
    ],
    "Kapan": [
        "Saat pendaftaran UMKM (jarang berubah)",
        "Saat profil dibuat/diperbarui",
        "Saat ada produk baru atau penyesuaian harga",
        "Bersamaan dengan pengunggahan data produk",
        "Opsional, diunggah berkala untuk demonstrasi keaslian",
        "Saat awal konfigurasi sistem atau ada kategori baru",
        "Saat registrasi akun baru",
        "Terjadi secara real-time saat transaksi/checkout",
        "Setelah pesanan selesai dikirim/diterima",
        "Ditulis dan diperbarui secara berkala oleh admin",
        "Dicatat otomatis secara real-time saat aktivitas terjadi"
    ],
    "Di mana": [
        "Database Relasional (Tabel Profil)",
        "File Storage (Folder Gambar) & URL di Database",
        "Database Relasional (Tabel Produk)",
        "File Storage (Folder Produk) & URL di Database",
        "File Storage (Folder Video) & URL di Database",
        "Database Relasional (Tabel Kategori)",
        "Database Relasional (Tabel Users)",
        "Database Relasional (Tabel Orders/Inquiries)",
        "Database Relasional (Tabel Reviews)",
        "Database Relasional & File Storage (Konten Artikel)",
        "File Log / Database Sistem"
    ],
    "Mengapa": [
        "Sebagai identitas resmi penjual perak Celuk",
        "Membangun kepercayaan dan branding visual pengrajin",
        "Menyediakan detail katalog produk yang transparan bagi pembeli",
        "Menjadi daya tarik utama visual untuk meyakinkan pembeli",
        "Menunjukkan keaslian proses handmade kerajinan perak",
        "Mempermudah navigasi dan penyaringan (filtering) produk",
        "Mengontrol autentikasi dan hak akses fitur aplikasi",
        "Mencatat dokumentasi transaksi dan memproses pesanan",
        "Sebagai bukti sosial (social proof) reputasi produk",
        "Edukasi nilai budaya perak Celuk dan optimasi SEO website",
        "Keperluan audit keamanan dan pelacakan error sistem"
    ],
    "Bagaimana": [
        "Diisi melalui form registrasi profil UMKM",
        "Diunggah langsung melalui form profil",
        "Diinput melalui form tambah/edit produk oleh pengrajin",
        "Diunggah dengan kompresi otomatis agar load website cepat",
        "Diunggah dalam format terkompresi (durasi maksimal 30 detik)",
        "Dikelola oleh admin melalui dashboard manajemen",
        "Melalui proses registrasi dengan enkripsi password satu arah",
        "Dibuat saat pembeli menekan tombol order / kirim inquiry",
        "Diinput pembeli melalui form ulasan produk",
        "Ditulis oleh admin menggunakan Rich Text Editor",
        "Dicatat otomatis oleh middleware / logger sistem"
    ]
}

# Membuat DataFrame
lifecycle_df = pd.DataFrame(karakteristik_data)

# Menyimpan dataframe ke CSV
lifecycle_df.to_csv('docs/lifecycle.csv', index=False)

# Menampilkan visualisasi tabel
print("="*60)
print("KARAKTERISTIK DATA MODEL (5W1H)")
print("="*60)
display(lifecycle_df)

============================================================
KARAKTERISTIK DATA MODEL (5W1H)
============================================================

,Jenis Data,Apa,Siapa,Kapan,Di mana,Mengapa,Bagaimana
0,Profil UMKM,"Teks terstruktur (Nama, pemilik, alamat, konta...",Admin / Pengrajin,Saat pendaftaran UMKM (jarang berubah),Database Relasional (Tabel Profil),Sebagai identitas resmi penjual perak Celuk,Diisi melalui form registrasi profil UMKM
1,Logo & foto bengkel,Gambar identitas (Logo dan dokumentasi tempat ...,Pengrajin,Saat profil dibuat/diperbarui,File Storage (Folder Gambar) & URL di Database,Membangun kepercayaan dan branding visual peng...,Diunggah langsung melalui form profil
2,Produk (teks),"Teks & Angka (Nama, kategori, harga, berat per...",Pengrajin,Saat ada produk baru atau penyesuaian harga,Database Relasional (Tabel Produk),Menyediakan detail katalog produk yang transpa...,Diinput melalui form tambah/edit produk oleh p...
3,Foto produk,Gambar detail (Visual produk dari berbagai sudut),Pengrajin,Bersamaan dengan pengunggahan data produk,File Storage (Folder Produk) & URL di Database,Menjadi daya tarik utama visual untuk meyakink...,Diunggah dengan kompresi otomatis agar load we...
4,Video,Video MP4 (Proses pembuatan perak filigree/det...,Pengrajin,"Opsional, diunggah berkala untuk demonstrasi k...",File Storage (Folder Video) & URL di Database,Menunjukkan keaslian proses handmade kerajinan...,Diunggah dalam format terkompresi (durasi maks...
5,Kategori,Teks pendek (Kategori perhiasan seperti cincin...,Admin,Saat awal konfigurasi sistem atau ada kategori...,Database Relasional (Tabel Kategori),Mempermudah navigasi dan penyaringan (filterin...,Dikelola oleh admin melalui dashboard manajemen
6,Pengguna,"Teks (Kredensial akun admin, pengrajin, dan pe...",Semua Pengguna,Saat registrasi akun baru,Database Relasional (Tabel Users),Mengontrol autentikasi dan hak akses fitur apl...,Melalui proses registrasi dengan enkripsi pass...
7,Pesanan/inquiry,Teks & Angka transaksional (Detail pesanan dan...,Pembeli,Terjadi secara real-time saat transaksi/checkout,Database Relasional (Tabel Orders/Inquiries),Mencatat dokumentasi transaksi dan memproses p...,Dibuat saat pembeli menekan tombol order / kir...
8,Ulasan,Teks & Angka (Feedback teks dan rating bintang...,Pembeli,Setelah pesanan selesai dikirim/diterima,Database Relasional (Tabel Reviews),Sebagai bukti sosial (social proof) reputasi p...,Diinput pembeli melalui form ulasan produk
9,Artikel budaya,"Teks & Gambar (Sejarah perak Celuk, teknik pem...",Admin,Ditulis dan diperbarui secara berkala oleh admin,Database Relasional & File Storage (Konten Art...,Edukasi nilai budaya perak Celuk dan optimasi ...,Ditulis oleh admin menggunakan Rich Text Editor
10,Log aktivitas,"Teks baris log (Riwayat sistem, waktu login, p...",Sistem (Otomatis),Dicatat otomatis secara real-time saat aktivit...,File Log / Database Sistem,Keperluan audit keamanan dan pelacakan error s...,Dicatat otomatis oleh middleware / logger sistem

In [4]:
import os
import pandas as pd

# Memastikan direktori docs ada
os.makedirs('docs', exist_ok=True)

# Pengaturan tampilan Pandas agar output tabel rapi dan konsisten
pd.options.display.float_format = "{:,.2f}".format
pd.options.display.width = 250

# ============================================================
# 1. ESTIMASI VOLUME DATA (DESA CELUK - 115 UMKM)
# ============================================================
asumsi_volume_data = {
    "Jenis Data": [
        "Profil UMKM",
        "Logo & foto bengkel",
        "Produk (teks)",
        "Foto produk",
        "Video",
        "Kategori",
        "Pengguna",
        "Pesanan/inquiry",
        "Ulasan",
        "Artikel budaya (teks + 2 foto)",
        "Log aktivitas"
    ],
    "Jumlah Unit": [
        "115",
        "345 (3/UMKM)",
        "2.300",
        "11.500 (5/produk)",
        "150",
        "30",
        "2.000",
        "5.000",
        "3.000",
        "100",
        "100.000 baris"
    ],
    "Ukuran Rata-rata": [
        "2 KB",
        "400 KB",
        "3 KB",
        "500 KB",
        "20 MB",
        "0.5 KB",
        "1 KB",
        "3 KB",
        "1 KB",
        "810 KB",
        "0.5 KB"
    ],
    "Total (MB)": [
        0.22,
        134.77,
        6.74,
        5615.23,
        3000.00,
        0.01,
        1.95,
        14.65,
        2.93,
        79.10,
        48.83
    ]
}

lifecycle_df = pd.DataFrame(asumsi_volume_data)
lifecycle_df.to_csv('docs/lifecycle_desa_celuk.csv', index=False)

# ============================================================
# 2. PEMISAH FAKTA VS ASUMSI
# ============================================================
fakta_vs_asumsi_df = pd.DataFrame({
    "Aspek / Angka": [
        "115 UMKM",
        "Biaya storage Rp2.600/bulan untuk 7.17 GB",
        "20 produk/UMKM, 5 foto/produk, 3 foto bengkel/UMKM",
        "Ukuran file (500 KB, 20 MB, dsb.)",
        "150 video, 100 artikel, 2.000 pengguna, dsb."
    ],
    "Status": [
        "Fakta",
        "Fakta",
        "Asumsi",
        "Asumsi",
        "Asumsi"
    ],
    "Dasar / Keterangan": [
        "Data Disperindag Gianyar 2020 (belum ada data resmi 2026)",
        "Tarif resmi Google Cloud Storage Jakarta (kurs Rp17.989)",
        "Berdasarkan estimasi kebutuhan rata-rata pengrajin",
        "Standar teknis kompresi WebP (gambar) dan MP4 (video)",
        "Skenario target sistem dalam 1 tahun pengembangan"
    ]
})
fakta_vs_asumsi_df.to_csv('docs/fakta_vs_asumsi.csv', index=False)

# ============================================================
# 3. RINGKASAN REKOMENDASI PENYIMPANAN
# ============================================================
total_kebutuhan_mb = lifecycle_df["Total (MB)"].sum()
cadangan_mb = total_kebutuhan_mb * 0.30
total_akhir_mb = total_kebutuhan_mb + cadangan_mb

ringkasan_penyimpanan = pd.DataFrame({
    "Metrik": [
        "Total Kebutuhan Bersih",
        "Cadangan (Buffer 30%)",
        "Total Kebutuhan Akhir (+ Cadangan)",
        "Rekomendasi Kapasitas Minimum"
    ],
    "Kapasitas (MB)": [
        f"{total_kebutuhan_mb:,.2f} MB",
        f"{cadangan_mb:,.2f} MB",
        f"{total_akhir_mb:,.2f} MB",
        "Minimal 12 GB"
    ],
    "Kapasitas (GB)": [
        f"{total_kebutuhan_mb / 1024:,.2f} GB",
        f"{cadangan_mb / 1024:,.2f} GB",
        f"{total_akhir_mb / 1024:,.2f} GB",
        "12.00 GB"
    ]
})

# Menampilkan Output dengan Format yang Sangat Rapi
print("\n" + "="*60)
print("1. ESTIMASI VOLUME DATA (DESA CELUK)")
print("="*60)
display(lifecycle_df)

print("\n" + "="*60)
print("2. RINGKASAN TOTAL PENYIMPANAN")
print("="*60)
display(ringkasan_penyimpanan)

print("\n" + "="*60)
print("3. PEMISAH FAKTA VS ASUMSI")
print("="*60)
display(fakta_vs_asumsi_df)

print("\n[INFO] Seluruh file tabel berhasil disimpan ke folder 'docs/'.")

============================================================
1. ESTIMASI VOLUME DATA (DESA CELUK)
============================================================

                        Jenis Data        Jumlah Unit Ukuran Rata-rata  Total (MB)
0                      Profil UMKM                115             2 KB        0.22
1              Logo & foto bengkel       345 (3/UMKM)           400 KB      134.77
2                    Produk (teks)              2.300             3 KB        6.74
3                      Foto produk  11.500 (5/produk)           500 KB    5,615.23
4                            Video                150            20 MB    3,000.00
5                         Kategori                 30           0.5 KB        0.01
6                         Pengguna              2.000             1 KB        1.95
7                  Pesanan/inquiry              5.000             3 KB       14.65
8                           Ulasan              3.000             1 KB        2.93
9   Artikel budaya (teks + 2 foto)                100           810 KB       79.10
10                   Log aktivitas      100.000 baris           0.5 KB       48.83

============================================================
2. RINGKASAN TOTAL PENYIMPANAN
============================================================

                               Metrik Kapasitas (MB) Kapasitas (GB)
0              Total Kebutuhan Bersih    8,904.43 MB        8.70 GB
1               Cadangan (Buffer 30%)    2,671.33 MB        2.61 GB
2  Total Kebutuhan Akhir (+ Cadangan)   11,575.76 MB       11.30 GB
3       Rekomendasi Kapasitas Minimum  Minimal 12 GB       12.00 GB

============================================================
3. PEMISAH FAKTA VS ASUMSI
============================================================

                                       Aspek / Angka  Status                                 Dasar / Keterangan
0                                           115 UMKM   Fakta  Data Disperindag Gianyar 2020 (belum ada data ...
1        Biaya storage Rp2.600/bulan untuk 7.17 GB   Fakta  Tarif resmi Google Cloud Storage Jakarta (kurs...
2  20 produk/UMKM, 5 foto/produk, 3 foto bengkel/...  Asumsi  Berdasarkan estimasi kebutuhan rata-rata pengr...
3                  Ukuran file (500 KB, 20 MB, dsb.)  Asumsi  Standar teknis kompresi WebP (gambar) dan MP4 ...
4       150 video, 100 artikel, 2.000 pengguna, dsb.  Asumsi  Skenario target sistem dalam 1 tahun pengembangan

[INFO] Seluruh file tabel berhasil disimpan ke folder 'docs/'.

In [6]:
from dataclasses import dataclass
import pandas as pd

KB_PER_MB = 1024
MB_PER_GB = 1024
CADANGAN = 0.30  # cadangan 30%

@dataclass
class JenisData:
    nama: str
    jumlah_unit: int
    ukuran_kb: float  # rata-rata per unit, dalam KB

    @property
    def total_kb(self) -> float:
        return self.jumlah_unit * self.ukuran_kb

    @property
    def total_mb(self) -> float:
        return self.total_kb / KB_PER_MB

JUMLAH_UMKM = 50
PRODUK_PER_UMKM = 20
JUMLAH_PRODUK = JUMLAH_UMKM * PRODUK_PER_UMKM  # 1.000

DATA = [
    JenisData("Profil UMKM (teks)", JUMLAH_UMKM, 2),
    JenisData("Logo & foto bengkel", JUMLAH_UMKM * 3, 400),
    JenisData("Produk (teks)", JUMLAH_PRODUK, 3),
    JenisData("Foto produk", JUMLAH_PRODUK * 5, 500),
    JenisData("Video produk/proses", 150, 20 * KB_PER_MB),  # 20 MB
    JenisData("Kategori", 30, 0.5),
    JenisData("Pengguna", 2000, 1),
    JenisData("Pesanan/inquiry", 5000, 3),
    JenisData("Ulasan & rating", 3000, 1),
    JenisData("Artikel budaya (teks+foto)", 100, 810),
    JenisData("Log aktivitas", 100_000, 0.5),
]

def main() -> None:
    # Membuat DataFrame untuk menyajikan data secara profesional
    df_data = pd.DataFrame({
        "Jenis Data": [d.nama for d in DATA],
        "Unit": [f"{d.jumlah_unit:,}" for d in DATA],
        "KB / Unit": [f"{d.ukuran_kb:,.1f}" for d in DATA],
        "Total (MB)": [d.total_mb for d in DATA]
    })

    total_mb = sum(d.total_mb for d in DATA)
    cadangan_mb = total_mb * CADANGAN
    grand_mb = total_mb + cadangan_mb

    # Menampilkan DataFrame utama
    print("="*70)
    print("ESTIMASI KONDISI AWAL (BULAN 0) - DETAILED")
    print("="*70)
    pd.options.display.float_format = "{:,.2f}".format
    display(df_data)

    # Menampilkan ringkasan kalkulasi
    df_ringkasan = pd.DataFrame({
        "Metrik Estimasi": [
            "Total Kebutuhan Bersih",
            "Alokasi Cadangan (30%)",
            "Grand Total Kebutuhan (Kapasitas Bersih + Cadangan)"
        ],
        "Kapasitas (MB)": [
            f"{total_mb:,.2f} MB",
            f"{cadangan_mb:,.2f} MB",
            f"{grand_mb:,.2f} MB"
        ],
        "Kapasitas (GB)": [
            f"{total_mb / MB_PER_GB:,.2f} GB",
            f"{cadangan_mb / MB_PER_GB:,.2f} GB",
            f"{grand_mb / MB_PER_GB:,.2f} GB"
        ]
    })

    print("\n" + "="*70)
    print("RINGKASAN TOTAL KAPASITAS")
    print("="*70)
    display(df_ringkasan)

if __name__ == "__main__":
    main()

======================================================================
ESTIMASI KONDISI AWAL (BULAN 0) - DETAILED
======================================================================

                    Jenis Data     Unit KB / Unit  Total (MB)
0           Profil UMKM (teks)       50       2.0        0.10
1          Logo & foto bengkel      150     400.0       58.59
2                Produk (teks)    1,000       3.0        2.93
3                  Foto produk    5,000     500.0    2,441.41
4          Video produk/proses      150  20,480.0    3,000.00
5                     Kategori       30       0.5        0.01
6                     Pengguna    2,000       1.0        1.95
7              Pesanan/inquiry    5,000       3.0       14.65
8              Ulasan & rating    3,000       1.0        2.93
9   Artikel budaya (teks+foto)      100     810.0       79.10
10               Log aktivitas  100,000       0.5       48.83

======================================================================
RINGKASAN TOTAL KAPASITAS
======================================================================

                                     Metrik Estimasi Kapasitas (MB) Kapasitas (GB)
0                             Total Kebutuhan Bersih    5,650.50 MB        5.52 GB
1                             Alokasi Cadangan (30%)    1,695.15 MB        1.66 GB
2  Grand Total Kebutuhan (Kapasitas Bersih + Cada...    7,345.65 MB        7.17 GB

In [ ]:
import sqlite3

# Membuat koneksi ke database SQLite lokal di Colab
conn = sqlite3.connect('katalog_perak_celuk.db')
cursor = conn.cursor()

# Membuat tabel-tabel sesuai skema relasional katalog perak Celuk
# Catatan: SQLite tidak memiliki tipe ENUM secara native, sehingga kita ganti dengan CHECK constraint

# 1. Tabel Pengguna
cursor.execute('''
CREATE TABLE IF NOT EXISTS pengguna (
  id_pengguna   INTEGER PRIMARY KEY AUTOINCREMENT,
  nama          TEXT NOT NULL,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  peran         TEXT NOT NULL CHECK(peran IN ('admin','pengrajin','pembeli')) DEFAULT 'pembeli',
  dibuat_pada   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
''')

# 2. Tabel UMKM
cursor.execute('''
CREATE TABLE IF NOT EXISTS umkm (
  id_umkm       INTEGER PRIMARY KEY AUTOINCREMENT,
  id_pengguna   INTEGER NOT NULL,
  nama_usaha    TEXT NOT NULL,
  pemilik       TEXT NOT NULL,
  alamat        TEXT NOT NULL,
  no_whatsapp   TEXT,
  deskripsi     TEXT,
  path_logo     TEXT,
  latitude      REAL,
  longitude     REAL,
  dibuat_pada   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_pengguna) REFERENCES pengguna(id_pengguna)
);
''')

# 3. Tabel Kategori
cursor.execute('''
CREATE TABLE IF NOT EXISTS kategori (
  id_kategori   INTEGER PRIMARY KEY AUTOINCREMENT,
  nama_kategori TEXT NOT NULL UNIQUE
);
''')

# 4. Tabel Produk
cursor.execute('''
CREATE TABLE IF NOT EXISTS produk (
  id_produk     INTEGER PRIMARY KEY AUTOINCREMENT,
  id_umkm       INTEGER NOT NULL,
  id_kategori   INTEGER NOT NULL,
  nama_produk   TEXT NOT NULL,
  deskripsi     TEXT,
  harga         REAL NOT NULL CHECK (harga >= 0),
  berat_gram    REAL,
  kadar_perak   TEXT,                     -- contoh: 925
  stok          INTEGER NOT NULL DEFAULT 0,
  dibuat_pada   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  diubah_pada   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_umkm) REFERENCES umkm(id_umkm) ON DELETE CASCADE,
  FOREIGN KEY (id_kategori) REFERENCES kategori(id_kategori)
);
''')

# 5. Tabel Media Produk
cursor.execute('''
CREATE TABLE IF NOT EXISTS media_produk (
  id_media      INTEGER PRIMARY KEY AUTOINCREMENT,
  id_produk     INTEGER NOT NULL,
  jenis         TEXT NOT NULL CHECK(jenis IN ('foto','video')),
  path_file     TEXT NOT NULL,
  ukuran_kb     INTEGER,
  urutan        INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (id_produk) REFERENCES produk(id_produk) ON DELETE CASCADE
);
''')

# 6. Tabel Pesanan
cursor.execute('''
CREATE TABLE IF NOT EXISTS pesanan (
  id_pesanan    INTEGER PRIMARY KEY AUTOINCREMENT,
  id_pengguna   INTEGER NOT NULL,
  status        TEXT NOT NULL CHECK(status IN ('inquiry','diproses','dikirim','selesai','batal')) DEFAULT 'inquiry',
  total_harga   REAL NOT NULL DEFAULT 0,
  dibuat_pada   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_pengguna) REFERENCES pengguna(id_pengguna)
);
''')

# 7. Tabel Detail Pesanan
cursor.execute('''
CREATE TABLE IF NOT EXISTS detail_pesanan (
  id_detail     INTEGER PRIMARY KEY AUTOINCREMENT,
  id_pesanan    INTEGER NOT NULL,
  id_produk     INTEGER NOT NULL,
  jumlah        INTEGER NOT NULL CHECK (jumlah > 0),
  harga_satuan  REAL NOT NULL,
  FOREIGN KEY (id_pesanan) REFERENCES pesanan(id_pesanan) ON DELETE CASCADE,
  FOREIGN KEY (id_produk) REFERENCES produk(id_produk)
);
''')

# 8. Tabel Ulasan
cursor.execute('''
CREATE TABLE IF NOT EXISTS ulasan (
  id_ulasan     INTEGER PRIMARY KEY AUTOINCREMENT,
  id_produk     INTEGER NOT NULL,
  id_pengguna   INTEGER NOT NULL,
  rating        INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  komentar      TEXT,
  dibuat_pada   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_produk) REFERENCES produk(id_produk) ON DELETE CASCADE,
  FOREIGN KEY (id_pengguna) REFERENCES pengguna(id_pengguna)
);
''')

# 9. Tabel Artikel
cursor.execute('''
CREATE TABLE IF NOT EXISTS artikel (
  id_artikel    INTEGER PRIMARY KEY AUTOINCREMENT,
  judul         TEXT NOT NULL,
  isi           TEXT NOT NULL,
  path_gambar   TEXT,
  dibuat_pada   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
''')

# 10. Tabel Log Aktivitas
cursor.execute('''
CREATE TABLE IF NOT EXISTS log_aktivitas (
  id_log        INTEGER PRIMARY KEY AUTOINCREMENT,
  id_pengguna   INTEGER,
  aksi          TEXT NOT NULL,
  keterangan    TEXT,
  waktu         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
''')

# Membuat index pendukung
cursor.execute("CREATE INDEX IF NOT EXISTS idx_produk_umkm ON produk (id_umkm);")
cursor.execute("CREATE INDEX IF NOT EXISTS idx_produk_kategori ON produk (id_kategori);")
cursor.execute("CREATE INDEX IF NOT EXISTS idx_log_waktu ON log_aktivitas (waktu);")

conn.commit()

# Memvalidasi pembuatan tabel
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

print("=== Database 'katalog_perak_celuk.db' Berhasil Dibuat ===")
print("Daftar tabel yang terbuat:")
for table in tables:
    print(f"- {table[0]}")

conn.close()

=== Database 'katalog_perak_celuk.db' Berhasil Dibuat ===
Daftar tabel yang terbuat:
- pengguna
- sqlite_sequence
- umkm
- kategori
- produk
- media_produk
- pesanan
- detail_pesanan
- ulasan
- artikel
- log_aktivitas

### **No. 2: Skenario Akuisisi Data & Estimasi Storage (1 Tahun)**

Topik yang dipilih adalah **Katalog UMKM Perak Desa Celuk**. Skenario akuisisi data dirancang berdasarkan estimasi pertumbuhan dan volume data berikut:

#### **Skenario Akuisisi Data**

1. **Pendaftaran UMKM & Produk**:
   * Pengrajin mendaftarkan profil UMKM mereka melalui formulir pendaftaran dan mengunggah produk secara berkala.
   * Diasumsikan terdapat **50 UMKM** terdaftar dengan masing-masing mengunggah **20 produk**.

2. **Manajemen Media Gambar**:
   * Foto diunggah bersamaan dengan pengisian data produk.
   * Skenario alokasi media: **5 foto per produk** dan **3 foto bengkel per UMKM**.
   * Foto dikompresi otomatis ke format modern (WebP) dengan ukuran rata-rata **500 KB per file**.

3. **Manajemen Media Video**:
   * Bersifat opsional untuk mendemonstrasikan keaslian produk.
   * Durasi video dibatasi maksimal **30 detik** dalam format MP4 terkompresi dengan ukuran rata-rata **20 MB per file**.
   * Dialokasikan total **150 video** di dalam sistem.

4. **Interaksi Pembeli**:
   * Pembeli menghasilkan data transaksi berupa pesanan (*inquiry*) saat proses checkout, serta memberikan ulasan setelah barang diterima.

5. **Konten Edukasi & Budaya**:
   * Admin mengelola kategori produk serta menulis artikel budaya.
   * Target konten: **100 artikel**, di mana setiap artikel dilengkapi dengan teks penjelasan dan **2 foto pendukung**.

6. **Log Sistem**:
   * Sistem secara otomatis mencatat riwayat aktivitas pengguna melalui lapisan middleware keamanan.

7. **Metode Penyimpanan**:
   * **Database Relasional**: Digunakan untuk menyimpan seluruh data teks terstruktur.
   * **File Storage**: Digunakan untuk menyimpan seluruh aset biner (foto dan video). Database hanya menyimpan tautan (*path/URL*) menuju file terkait.

---

#### **Asumsi Pertumbuhan Data**
* Angka di atas merupakan kondisi awal (**Bulan 0**).
* Diasumsikan seluruh jenis data mengalami pertumbuhan kumulatif sebesar **10% per bulan** secara majemuk dengan formula:
  $$S(n) = S_0 \times 1.1^n$$
* Alokasi penyimpanan akhir ditambahkan **cadangan (buffer) sebesar 30%** untuk menjaga keandalan sistem.

In [3]:
from dataclasses import dataclass
import os
import pandas as pd

# Pengaturan tampilan Pandas agar tabel rapi
pd.options.display.float_format = "{:,.2f}".format
pd.options.display.width = 250
pd.options.display.max_columns = 30

# ============================================================
# 1. KONSTANTA & PARAMETER ESTIMASI
# ============================================================
KB_PER_MB = 1024
MB_PER_GB = 1024
CADANGAN_PERSEN = 0.30       # Alokasi buffer cadangan 30%
PERTUMBUHAN_BULANAN = 0.10   # Tingkat pertumbuhan data 10% per bulan
DURASI_PROYEKSI = 12         # Proyeksi untuk jangka waktu 12 bulan

JUMLAH_UMKM = 50
PRODUK_PER_UMKM = 20
JUMLAH_PRODUK = JUMLAH_UMKM * PRODUK_PER_UMKM

# ============================================================
# 2. STRUKTUR DATA & ESTIMASI BULAN 0
# ============================================================
@dataclass
class KategoriData:
    nama: str
    jumlah_unit: int
    ukuran_kb_per_unit: float
    deskripsi: str = ""

    @property
    def total_kb(self) -> float:
        return self.jumlah_unit * self.ukuran_kb_per_unit

    @property
    def total_mb(self) -> float:
        return self.total_kb / KB_PER_MB


# Daftar rincian data kondisi awal
DAFTAR_DATA = [
    KategoriData("Profil UMKM (teks)",        JUMLAH_UMKM,         2.0,            "50 UMKM x 2 KB"),
    KategoriData("Logo & foto bengkel",       JUMLAH_UMKM * 3,     400.0,          "3 foto/UMKM x 400 KB"),
    KategoriData("Produk (teks)",             JUMLAH_PRODUK,       3.0,            "1.000 produk x 3 KB"),
    KategoriData("Foto produk",               JUMLAH_PRODUK * 5,   500.0,          "5 foto/produk x 500 KB (WebP)"),
    KategoriData("Video produk/proses",       150,                 20480.0,        "150 video x 20 MB (MP4, maks 30 detik)"),
    KategoriData("Kategori",                  30,                  0.5,            "30 kategori x 0,5 KB"),
    KategoriData("Pengguna",                  2000,                1.0,            "2.000 akun x 1 KB"),
    KategoriData("Pesanan/inquiry",           5000,                3.0,            "5.000 pesanan x 3 KB"),
    KategoriData("Ulasan & rating",           3000,                1.0,            "3.000 ulasan x 1 KB"),
    KategoriData("Artikel budaya (teks+foto)", 100,                810.0,          "100 artikel x 810 KB (teks + 2 foto)"),
    KategoriData("Log aktivitas",             100000,              0.5,            "100.000 baris x 0,5 KB"),
]

# Membuat DataFrame Kondisi Awal
tabel_awal = pd.DataFrame({
    "Jenis Data": [d.nama for d in DAFTAR_DATA],
    "Jumlah Unit": [d.jumlah_unit for d in DAFTAR_DATA],
    "Ukuran/Unit (KB)": [d.ukuran_kb_per_unit for d in DAFTAR_DATA],
    "Total (KB)": [d.total_kb for d in DAFTAR_DATA],
    "Total (MB)": [d.total_mb for d in DAFTAR_DATA],
    "Dasar Hitungan": [d.deskripsi for d in DAFTAR_DATA],
})
tabel_awal["Porsi (%)"] = (tabel_awal["Total (MB)"] / tabel_awal["Total (MB)"].sum()) * 100

total_awal_mb = tabel_awal["Total (MB)"].sum()
cadangan_awal_mb = total_awal_mb * CADANGAN_PERSEN

print("=== A. KONDISI AWAL (BULAN 0) ===")
display(tabel_awal)
print(f"Total Kebutuhan Bersih : {total_awal_mb:,.2f} MB ({total_awal_mb / MB_PER_GB:.2f} GB)")
print(f"Alokasi Cadangan (30%) : {cadangan_awal_mb:,.2f} MB")
print(f"Total + Cadangan       : {total_awal_mb + cadangan_awal_mb:,.2f} MB ({(total_awal_mb + cadangan_awal_mb) / MB_PER_GB:.2f} GB)\n")

# Validasi total awal dengan baseline
assert round(total_awal_mb, 2) == 5650.50, "Error: Total awal tidak sinkron dengan data kelompok!"

# ============================================================
# 3. PROYEKSI AKUMULASI STORAGE 12 BULAN
# ============================================================
list_proyeksi = []
kapasitas_sebelumnya = None

for bulan in range(DURASI_PROYEKSI + 1):
    faktor_pertumbuhan = (1 + PERTUMBUHAN_BULANAN) ** bulan
    total_mb = total_awal_mb * faktor_pertumbuhan
    tambahan_mb = 0.0 if kapasitas_sebelumnya is None else total_mb - kapasitas_sebelumnya
    total_dengan_cadangan_mb = total_mb * (1 + CADANGAN_PERSEN)

    list_proyeksi.append({
        "Bulan": bulan,
        "Faktor Pertumbuhan": faktor_pertumbuhan,
        "Total (MB)": total_mb,
        "Total (GB)": total_mb / MB_PER_GB,
        "Tambahan Bulanan (MB)": tambahan_mb,
        "Total + Cadangan (MB)": total_dengan_cadangan_mb,
        "Total + Cadangan (GB)": total_dengan_cadangan_mb / MB_PER_GB,
    })
    kapasitas_sebelumnya = total_mb

proyeksi_df = pd.DataFrame(list_proyeksi)
print("=== B. PROYEKSI TOTAL STORAGE 12 BULAN ===")
display(proyeksi_df)

# ============================================================
# 4. PROYEKSI DETAILED PER JENIS DATA (MB)
# ============================================================
proyeksi_per_jenis = pd.DataFrame(
    {
        f"Bulan {b}": [d.total_mb * (1 + PERTUMBUHAN_BULANAN) ** b for d in DAFTAR_DATA]
        for b in range(DURASI_PROYEKSI + 1)
    },
    index=[d.nama for d in DAFTAR_DATA],
)
proyeksi_per_jenis.loc["TOTAL"] = proyeksi_per_jenis.sum()

print("\n=== C. PROYEKSI PER JENIS DATA (MB) ===")
display(proyeksi_per_jenis)

# Validasi konsistensi kalkulasi
assert abs(proyeksi_per_jenis.loc["TOTAL", f"Bulan {DURASI_PROYEKSI}"] - proyeksi_df["Total (MB)"].iloc[-1]) < 1e-6

# ============================================================
# 5. RINGKASAN REKOMENDASI BULAN KE-12
# ============================================================
faktor_akhir = (1 + PERTUMBUHAN_BULANAN) ** DURASI_PROYEKSI
kapasitas_akhir_mb = total_awal_mb * faktor_akhir
kapasitas_akhir_cadangan_mb = kapasitas_akhir_mb * (1 + CADANGAN_PERSEN)
kapasitas_akhir_cadangan_gb = kapasitas_akhir_cadangan_mb / MB_PER_GB
tambahan_tahunan_mb = kapasitas_akhir_mb - total_awal_mb

ringkasan_df = pd.DataFrame({
    "Keterangan": [
        "Total Awal (Bulan 0)",
        "Faktor Pertumbuhan Komulatif 12 Bulan (1.1^12)",
        "Kebutuhan Bersih Bulan ke-12",
        "Akumulasi Penambahan Data 1 Tahun",
        "Alokasi Cadangan (30%) Bulan ke-12",
        "Kebutuhan Total Bulan ke-12 + Cadangan",
        "Rekomendasi Kapasitas Penyediaan (Pembulatan Atas)"
    ],
    "Nilai": [
        f"{total_awal_mb:,.2f} MB ({total_awal_mb / MB_PER_GB:.2f} GB)",
        f"{faktor_akhir:.4f} kali",
        f"{kapasitas_akhir_mb:,.2f} MB ({kapasitas_akhir_mb / MB_PER_GB:.2f} GB)",
        f"{tambahan_tahunan_mb:,.2f} MB ({tambahan_tahunan_mb / MB_PER_GB:.2f} GB)",
        f"{kapasitas_akhir_mb * CADANGAN_PERSEN:,.2f} MB",
        f"{kapasitas_akhir_cadangan_mb:,.2f} MB ({kapasitas_akhir_cadangan_gb:.2f} GB)",
        f"Minimal {int(kapasitas_akhir_cadangan_gb) + 1} GB"
    ]
})

print("\n=== D. RINGKASAN ESTIMASI BULAN KE-12 ===")
display(ringkasan_df)

# ============================================================
# 6. PENYIMPANAN DATASET HASIL
# ============================================================
os.makedirs("docs", exist_ok=True)
tabel_awal.to_csv("docs/storage_kondisi_awal.csv", index=False)
proyeksi_df.to_csv("docs/storage_proyeksi_12_bulan.csv", index=False)
proyeksi_per_jenis.to_csv("docs/storage_per_jenis_data.csv")
ringkasan_df.to_csv("docs/storage_ringkasan.csv", index=False)
print("\n[INFO] Seluruh file estimasi berhasil diperbarui dan disimpan di folder 'docs/'.")

=== A. KONDISI AWAL (BULAN 0) ===

                    Jenis Data  Jumlah Unit  Ukuran/Unit (KB)   Total (KB)  Total (MB)                          Dasar Hitungan  Porsi (%)
0           Profil UMKM (teks)           50              2.00       100.00        0.10                          50 UMKM x 2 KB       0.00
1          Logo & foto bengkel          150            400.00    60,000.00       58.59                    3 foto/UMKM x 400 KB       1.04
2                Produk (teks)         1000              3.00     3,000.00        2.93                     1.000 produk x 3 KB       0.05
3                  Foto produk         5000            500.00 2,500,000.00    2,441.41           5 foto/produk x 500 KB (WebP)      43.21
4          Video produk/proses          150         20,480.00 3,072,000.00    3,000.00  150 video x 20 MB (MP4, maks 30 detik)      53.09
5                     Kategori           30              0.50        15.00        0.01                    30 kategori x 0,5 KB       0.00
6                     Pengguna         2000              1.00     2,000.00        1.95                       2.000 akun x 1 KB       0.03
7              Pesanan/inquiry         5000              3.00    15,000.00       14.65                    5.000 pesanan x 3 KB       0.26
8              Ulasan & rating         3000              1.00     3,000.00        2.93                     3.000 ulasan x 1 KB       0.05
9   Artikel budaya (teks+foto)          100            810.00    81,000.00       79.10    100 artikel x 810 KB (teks + 2 foto)       1.40
10               Log aktivitas       100000              0.50    50,000.00       48.83                  100.000 baris x 0,5 KB       0.86

Total Kebutuhan Bersih : 5,650.50 MB (5.52 GB)
Alokasi Cadangan (30%) : 1,695.15 MB
Total + Cadangan       : 7,345.65 MB (7.17 GB)

=== B. PROYEKSI TOTAL STORAGE 12 BULAN ===

    Bulan  Faktor Pertumbuhan  Total (MB)  Total (GB)  Tambahan Bulanan (MB)  Total + Cadangan (MB)  Total + Cadangan (GB)
0       0                1.00    5,650.50        5.52                   0.00               7,345.65                   7.17
1       1                1.10    6,215.55        6.07                 565.05               8,080.22                   7.89
2       2                1.21    6,837.11        6.68                 621.56               8,888.24                   8.68
3       3                1.33    7,520.82        7.34                 683.71               9,777.07                   9.55
4       4                1.46    8,272.90        8.08                 752.08              10,754.77                  10.50
5       5                1.61    9,100.19        8.89                 827.29              11,830.25                  11.55
6       6                1.77   10,010.21        9.78                 910.02              13,013.27                  12.71
7       7                1.95   11,011.23       10.75               1,001.02              14,314.60                  13.98
8       8                2.14   12,112.35       11.83               1,101.12              15,746.06                  15.38
9       9                2.36   13,323.59       13.01               1,211.24              17,320.67                  16.91
10     10                2.59   14,655.95       14.31               1,332.36              19,052.73                  18.61
11     11                2.85   16,121.54       15.74               1,465.59              20,958.01                  20.47
12     12                3.14   17,733.70       17.32               1,612.15              23,053.81                  22.51

=== C. PROYEKSI PER JENIS DATA (MB) ===

                            Bulan 0  Bulan 1  Bulan 2  Bulan 3  Bulan 4  Bulan 5   Bulan 6   Bulan 7   Bulan 8   Bulan 9  Bulan 10  Bulan 11  Bulan 12
Profil UMKM (teks)             0.10     0.11     0.12     0.13     0.14     0.16      0.17      0.19      0.21      0.23      0.25      0.28      0.31
Logo & foto bengkel           58.59    64.45    70.90    77.99    85.79    94.37    103.80    114.18    125.60    138.16    151.98    167.17    183.89
Produk (teks)                  2.93     3.22     3.54     3.90     4.29     4.72      5.19      5.71      6.28      6.91      7.60      8.36      9.19
Foto produk                2,441.41 2,685.55 2,954.10 3,249.51 3,574.46 3,931.91  4,325.10  4,757.61  5,233.37  5,756.71  6,332.38  6,965.62  7,662.18
Video produk/proses        3,000.00 3,300.00 3,630.00 3,993.00 4,392.30 4,831.53  5,314.68  5,846.15  6,430.77  7,073.84  7,781.23  8,559.35  9,415.29
Kategori                       0.01     0.02     0.02     0.02     0.02     0.02      0.03      0.03      0.03      0.03      0.04      0.04      0.05
Pengguna                       1.95     2.15     2.36     2.60     2.86     3.15      3.46      3.81      4.19      4.61      5.07      5.57      6.13
Pesanan/inquiry               14.65    16.11    17.72    19.50    21.45    23.59     25.95     28.55     31.40     34.54     37.99     41.79     45.97
Ulasan & rating                2.93     3.22     3.54     3.90     4.29     4.72      5.19      5.71      6.28      6.91      7.60      8.36      9.19
Artikel budaya (teks+foto)    79.10    87.01    95.71   105.28   115.81   127.39    140.13    154.15    169.56    186.52    205.17    225.69    248.25
Log aktivitas                 48.83    53.71    59.08    64.99    71.49    78.64     86.50     95.15    104.67    115.13    126.65    139.31    153.24
TOTAL                      5,650.50 6,215.55 6,837.11 7,520.82 8,272.90 9,100.19 10,010.21 11,011.23 12,112.35 13,323.59 14,655.95 16,121.54 17,733.70

=== D. RINGKASAN ESTIMASI BULAN KE-12 ===

                                          Keterangan                    Nilai
0                               Total Awal (Bulan 0)    5,650.50 MB (5.52 GB)
1     Faktor Pertumbuhan Komulatif 12 Bulan (1.1^12)              3.1384 kali
2                       Kebutuhan Bersih Bulan ke-12  17,733.70 MB (17.32 GB)
3                  Akumulasi Penambahan Data 1 Tahun  12,083.20 MB (11.80 GB)
4                 Alokasi Cadangan (30%) Bulan ke-12              5,320.11 MB
5             Kebutuhan Total Bulan ke-12 + Cadangan  23,053.81 MB (22.51 GB)
6  Rekomendasi Kapasitas Penyediaan (Pembulatan A...            Minimal 23 GB

[INFO] Seluruh file estimasi berhasil diperbarui dan disimpan di folder 'docs/'.

### **Mengapa Multimedia Sebaiknya Tidak Disimpan sebagai BLOB di Database**

Berkas multimedia (seperti gambar, logo, dan video) sebaiknya disimpan di **File Storage** (misalnya Google Cloud Storage), sedangkan database cukup mencatat **path (jalur file) dan metadatanya**.

Berikut adalah beberapa alasan utama mengapa pendekatan ini jauh lebih baik:

1. **Ukuran Database Menjadi Terlalu Besar**
   * Pada data katalog UMKM ini, berkas media (foto, video, dan logo) mencakup **5.500 MB** dari total **5.650 MB** (sekitar **97%**), sedangkan data teks hanya sekitar **71 MB**.
   * Jika semua media disimpan sebagai BLOB, ukuran database akan membengkak hingga **79 kali lipat** dan berpotensi mendekati **17 GB** pada bulan ke-12.

2. **Proses Backup dan Restore yang Lambat**
   * Setiap kali melakukan backup, sistem harus menyalin seluruh file media yang berukuran besar, padahal file tersebut jarang sekali berubah. Hal ini membuat proses pemeliharaan database menjadi tidak efisien.

3. **Penurunan Performa Query**
   * File besar yang disimpan di dalam database akan memenuhi memori *cache* dan memperberat log transaksi saat proses unggah (*upload*).
   * Akibatnya, query sederhana (seperti menampilkan daftar produk) akan ikut melambat secara signifikan.

4. **Efisiensi Biaya (Cost & Scaling)**
   * Penyimpanan pada database jauh lebih mahal dan lebih sulit untuk ditingkatkan skalanya (*scaling*) dibandingkan dengan layanan *Object Storage* khusus seperti **Google Cloud Storage**.

5. **Kemudahan Penyajian ke Pengguna (Delivery & Speed)**
   * Berkas yang disimpan dalam bentuk BLOB harus dibaca melalui aplikasi backend terlebih dahulu sebelum dikirim ke pembeli, sehingga tidak bisa memanfaatkan fitur **CDN (Content Delivery Network)**, *browser caching*, atau *video streaming* secara langsung.

6. **Kemudahan Pengolahan File**
   * Proses manipulasi media seperti pembuatan gambar mini (*thumbnail*), kompresi otomatis, atau konversi format (misalnya ke WebP) jauh lebih mudah dilakukan jika file berada di penyimpanan biasa.

---

#### **Penerapan pada Skema Database Kita:**
* **Tabel `media_produk`**: Menyimpan referensi berupa `path_file`, `ukuran_kb`, dan `urutan` gambar.
* **Tabel `umkm` & `artikel`**: Kolom `path_logo` dan `path_gambar` hanya menyimpan string URL/path menuju file storage terkait.
* **Antisipasi Risiko**: Menyimpan file di luar database memiliki risiko munculnya *file yatim* (file tetap ada di storage meskipun datanya sudah terhapus di database). Hal ini dapat diatasi dengan mekanisme pembersihan terjadwal (*cron job*).